'use client';

import { useMemo, useState } from 'react';

type Section = 'Home' | 'Assistant' | 'Projects' | 'Memory' | 'Library' | 'Settings';
type Task = { id: number; title: string; meta: string; done: boolean };
const nav: { name: Section; icon: string }[] = [
  { name: 'Home', icon: '⌂' }, { name: 'Assistant', icon: '✳' }, { name: 'Projects', icon: '▦' },
  { name: 'Memory', icon: '◷' }, { name: 'Library', icon: '▤' }, { name: 'Settings', icon: '⚙' },
];
const initialTasks: Task[] = [
  { id: 1, title: 'Review the ORBIT product brief', meta: 'Today · Planning', done: false },
  { id: 2, title: 'Map the first workspace flow', meta: 'Today · Product', done: false },
  { id: 3, title: 'Collect interface references', meta: 'Tomorrow · Design', done: true },
];
const projects = [
  { title: 'ORBIT', type: 'Personal workspace', progress: 32, color: 'violet' },
  { title: 'Learning studio', type: 'Education', progress: 68, color: 'blue' },
  { title: 'Career roadmap', type: 'Personal', progress: 15, color: 'green' },
];

export default function Page() {
  const [active, setActive] = useState<Section>('Home');
  const [tasks, setTasks] = useState(initialTasks);
  const [query, setQuery] = useState('');
  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState<string[]>([]);
  const [notice, setNotice] = useState('');
  const completed = tasks.filter(t => t.done).length;
  const filtered = useMemo(() => projects.filter(p => p.title.toLowerCase().includes(query.toLowerCase())), [query]);
  function addTask() {
    const title = window.prompt('What would you like to add?');
    if (title?.trim()) setTasks(old => [...old, { id: Date.now(), title: title.trim(), meta: 'Just added · Inbox', done: false }]);
  }
  function sendMessage() {
    if (!message.trim()) return;
    setMessages(old => [...old, message.trim()]); setMessage('');
  }
  return <main className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="#home" onClick={() => setActive('Home')}><span className="brand-mark">O</span><span>ORBIT<small>PERSONAL WORKSPACE</small></span></a>
      <div className="side-label">WORKSPACE</div>
      <nav aria-label="Main navigation">{nav.map(item => <button key={item.name} className={`nav-item ${active === item.name ? 'selected' : ''}`} onClick={() => setActive(item.name)}><span className="nav-icon">{item.icon}</span>{item.name}{item.name === 'Assistant' && <span className="nav-dot" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="plan-card"><span className="plan-icon">✦</span><div><b>Your space, your rules</b><p>Private by design. You stay in control.</p></div></div><button className="profile"><span className="avatar">SD</span><span><b>Swapnil Dalvi</b><small>Personal account</small></span><span className="more">···</span></button></div>
    </aside>
    <section className="main-area">
      <header className="topbar"><div className="mobile-brand"><span className="brand-mark">O</span> ORBIT</div><div className="breadcrumb"><span>Workspace</span><span className="crumb-sep">/</span><b>{active}</b></div><div className="top-actions"><label className="searchbox"><span>⌕</span><input aria-label="Search workspace" placeholder="Search anything..." value={query} onChange={e => setQuery(e.target.value)} /><kbd>⌘ K</kbd></label><button className="icon-button" aria-label="Notifications" onClick={() => setNotice('You’re all caught up.')}>♧</button><button className="avatar small-avatar" aria-label="Account">SD</button></div></header>
      <div className="content">
        {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss">×</button></div>}
        {active === 'Home' && <>
          <div className="welcome-row"><div><div className="eyebrow">MONDAY, SEPTEMBER 28</div><h1>Good morning, Swapnil <span>✦</span></h1><p className="subhead">A little clarity goes a long way. Here’s your space today.</p></div><button className="primary-button" onClick={addTask}>＋ <span>New task</span></button></div>
          <div className="hero-card"><div className="hero-copy"><div className="hero-kicker"><span className="live-dot" /> YOUR DAY AT A GLANCE</div><h2>Make room for<br/>what matters.</h2><p>Small, intentional steps. Your projects and thoughts, all in one place.</p><button className="hero-link" onClick={() => setActive('Projects')}>Explore your workspace <span>→</span></button></div><div className="orbit-art" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-ring ring-three"/><div className="orbit-core">O</div><span className="orbit-star star-a">✦</span><span className="orbit-star star-b">✧</span><span className="orbit-star star-c">·</span></div></div>
          <div className="section-heading"><div><h2>Your focus</h2><p>Keep the next steps within reach.</p></div><button className="text-button" onClick={() => setActive('Projects')}>View projects <span>→</span></button></div>
          <div className="focus-grid"><div className="panel task-panel"><div className="panel-head"><div><h3>Today’s tasks</h3><p>{completed} of {tasks.length} completed</p></div><button className="round-plus" onClick={addTask} aria-label="Add task">＋</button></div><div className="progress-track"><span style={{width: `${tasks.length ? completed / tasks.length * 100 : 0}%`}}/></div><div className="task-list">{tasks.map(task => <label className={`task-row ${task.done ? 'is-done' : ''}`} key={task.id}><input type="checkbox" checked={task.done} onChange={e => setTasks(old => old.map(t => t.id === task.id ? {...t, done: e.target.checked} : t))}/><span className="task-check"/><span className="task-text"><b>{task.title}</b><small>{task.meta}</small></span><span className="task-menu">···</span></label>)}</div><button className="panel-footer" onClick={() => setNotice('Task list is up to date.')}>See all tasks <span>→</span></button></div>
          <div className="panel projects-panel"><div className="panel-head"><div><h3>In progress</h3><p>Your active projects</p></div><button className="more-link" onClick={() => setActive('Projects')}>All <span>→</span></button></div><div className="project-list">{projects.slice(0,3).map((p,i) => <button className="project-row" key={p.title} onClick={() => setActive('Projects')}><span className={`project-icon ${p.color}`}>{['◈','▧','✳'][i]}</span><span className="project-details"><b>{p.title}</b><small>{p.type}</small><span className="mini-track"><i style={{width:`${p.progress}%`}}/></span></span><span className="project-percent">{p.progress}%</span></button>)}</div><button className="panel-footer" onClick={() => setActive('Projects')}>Open project space <span>→</span></button></div></div>
          <div className="bottom-grid"><div className="panel quick-panel"><div className="panel-head"><div><h3>Quick access</h3><p>Pick up where you left off</p></div></div><div className="quick-links"><button onClick={() => setActive('Assistant')}><span className="quick-icon lilac">✳</span><span><b>Ask ORBIT</b><small>Think something through</small></span><span className="arrow">↗</span></button><button onClick={() => setActive('Memory')}><span className="quick-icon peach">◷</span><span><b>Saved thoughts</b><small>Your notes and memory</small></span><span className="arrow">↗</span></button><button onClick={() => setActive('Library')}><span className="quick-icon mint">▤</span><span><b>Library</b><small>Files and references</small></span><span className="arrow">↗</span></button></div></div><div className="quote-card"><span className="quote-mark">“</span><p>Focus is not about doing more. It’s about making space for what matters.</p><span className="quote-credit">A NOTE TO SELF</span><div className="quote-spark">✧</div></div></div>
        </>}
        {active === 'Assistant' && <div className="page-view"><div className="eyebrow">YOUR THINKING PARTNER</div><h1>What’s on your mind?</h1><p className="subhead">Explore ideas, organize thoughts, or work through a problem. This demo keeps responses local.</p><div className="chat-box"><div className="assistant-welcome"><span className="assistant-symbol">✳</span><h2>Hi Swapnil, I’m ORBIT.</h2><p>Tell me what you’re working on. We can break it into clear next steps.</p><div className="suggestions"><button onClick={() => setMessage('Help me plan my day')}>Help me plan my day <span>↗</span></button><button onClick={() => setMessage('Turn an idea into a project')}>Turn an idea into a project <span>↗</span></button><button onClick={() => setMessage('Summarize my notes')}>Summarize my notes <span>↗</span></button></div></div>{messages.map((m,i)=><div className="user-message" key={i}>{m}</div>)}{messages.length>0 && <div className="demo-reply">I’ve captured that in this prototype. When AI is connected, ORBIT will help you work through it with your permission.</div>}<form className="chat-compose" onSubmit={e => {e.preventDefault();sendMessage();}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask or share something..." aria-label="Message ORBIT"/><button className="send-button" type="submit" aria-label="Send message">↑</button></form><div className="demo-note">Prototype mode · No message is sent to an AI service</div></div></div>}
        {active === 'Projects' && <div className="page-view"><div className="eyebrow">YOUR WORK, ORGANIZED</div><div className="page-title-row"><div><h1>Projects</h1><p className="subhead">A home for the things you’re building.</p></div><button className="primary-button" onClick={() => setNotice('Project creation will be enabled in the next data milestone.')}>＋ New project</button></div><label className="wide-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a project..."/></label><div className="project-cards">{filtered.map((p,i)=><article className="project-card" key={p.title}><div className={`project-icon large ${p.color}`}>{['◈','▧','✳'][projects.findIndex(x=>x.title===p.title)]}</div><span className="card-menu">···</span><h3>{p.title}</h3><p>{p.type}</p><div className="card-progress-label"><span>Progress</span><b>{p.progress}%</b></div><div className="progress-track"><span style={{width:`${p.progress}%`}}/></div><button className="panel-footer" onClick={()=>setNotice(`${p.title} selected. Project details are coming in the next milestone.`)}>Open project <span>→</span></button></article>)}</div>{filtered.length===0 && <div className="empty-state">No projects match “{query}”. Try another search.</div>}</div>}
        {active === 'Memory' && <div className="page-view"><div className="eyebrow">YOUR CONTEXT, YOUR CONTROL</div><h1>Memory</h1><p className="subhead">Keep useful notes close. Nothing here is shared without your say-so.</p><div className="memory-callout"><span>◷</span><div><b>Personal memory is in preview</b><p>This area will hold notes you choose to save, with controls to edit or remove them.</p></div></div><div className="empty-state"><span className="empty-icon">✧</span><h3>A clear space for your thoughts</h3><p>Your saved notes and searchable memory will appear here.</p><button className="secondary-button" onClick={()=>setNotice('Note capture will be available in the next milestone.')}>＋ Create a note</button></div></div>}
        {active === 'Library' && <div className="page-view"><div className="eyebrow">YOUR REFERENCE SHELF</div><h1>Library</h1><p className="subhead">Files, links, and resources gathered in one place.</p><div className="library-toolbar"><label className="wide-search"><span>⌕</span><input placeholder="Search your library..." aria-label="Search library"/></label><button className="secondary-button" onClick={()=>setNotice('File upload will be added after the first UI review.')}>＋ Add resource</button></div><div className="empty-state"><span className="empty-icon">▤</span><h3>Your library is ready when you are</h3><p>Upload or save resources to build a personal reference shelf.</p></div></div>}
        {active === 'Settings' && <div className="page-view"><div className="eyebrow">MAKE ORBIT YOURS</div><h1>Settings</h1><p className="subhead">Manage your workspace preferences and privacy.</p><div className="settings-list"><section><h3>Appearance</h3><div className="setting-row"><div><b>Theme</b><small>Light-first interface preview</small></div><span className="setting-value">Light <span>⌄</span></span></div></section><section><h3>Privacy & control</h3><div className="setting-row"><div><b>Assistant permissions</b><small>Actions require your approval in this prototype</small></div><span className="status-pill">Approval-first</span></div><div className="setting-row"><div><b>Personal data</b><small>Memory and integrations are not connected yet</small></div><span className="status-pill muted">Not connected</span></div></section><section><h3>About</h3><div className="setting-row"><div><b>ORBIT workspace</b><small>Web prototype · Version 0.1</small></div><span className="setting-value">Details</span></div></section></div></div>}
      </div>
      <footer className="app-footer"><span>ORBIT <span className="footer-dot">·</span> A space to think clearly.</span><span>Private by design <span className="lock">◇</span></span></footer>
    </section>
    <nav className="mobile-nav" aria-label="Mobile navigation">{nav.filter(n=>n.name!=='Settings').map(item=><button key={item.name} className={active===item.name?'active':''} onClick={()=>setActive(item.name)}><span>{item.icon}</span><small>{item.name}</small></button>)}<button className={active==='Settings'?'active':''} onClick={()=>setActive('Settings')}><span>•••</span><small>More</small></button></nav>
  </main>;
}
